// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATo51Wic8YkfDvKIbkFbzti1U8iDA76BU',
    appId: '1:966603479235:web:f1ad4a7bdf4373fee8aa76',
    messagingSenderId: '966603479235',
    projectId: 'uberclone-239da',
    authDomain: 'uberclone-239da.firebaseapp.com',
    storageBucket: 'uberclone-239da.appspot.com',
    measurementId: 'G-X6MFBQDJXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ_vWo2KI-md0iOQl4rN86YVchlWLa5c4',
    appId: '1:966603479235:android:e70c4bf70cbb2a89e8aa76',
    messagingSenderId: '966603479235',
    projectId: 'uberclone-239da',
    storageBucket: 'uberclone-239da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zRZ9akOl_KtlEDcTgGmEk-4REo6nBXA',
    appId: '1:966603479235:ios:b71c51614b6046efe8aa76',
    messagingSenderId: '966603479235',
    projectId: 'uberclone-239da',
    storageBucket: 'uberclone-239da.appspot.com',
    iosClientId:
        '966603479235-9ht5ql44ct3a2341kkggb1fo7eduqgl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1zRZ9akOl_KtlEDcTgGmEk-4REo6nBXA',
    appId: '1:966603479235:ios:764190648af70ce1e8aa76',
    messagingSenderId: '966603479235',
    projectId: 'uberclone-239da',
    storageBucket: 'uberclone-239da.appspot.com',
    iosClientId:
        '966603479235-3a2jeh0c58kmma86rniv7sbkpms256nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberClone.RunnerTests',
  );
}
